project_id = "halfhlgkutibalmuuohx"

[functions.schedule-workout-sessions]
verify_jwt = true

[functions.create-personal-checkout]
verify_jwt = true

[functions.create-client-subscription]
verify_jwt = true

[functions.manage-subscription]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.generate-body-type-images]
verify_jwt = true